site_name: OpenShift Pipelines Demo
theme:
  name: material
pages:
  - Home: index.md
  - Setup: setup.md
  - Deployment: deployment.md
  - 'The Pipeline': pipeline.md
  - Automations: automations.md
