apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mkdocs-demo
  name: mkdocs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs-demo
  template:
    metadata:
      labels:
        app: mkdocs-demo
    spec:
      initContainers:
      - image: quay.io/pbertera/mkdocs:latest
        imagePullPolicy: Always
        name: mkdocs-builder
        args: ["build", "-c", "-d", "html"]
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/data
          name: mkdocs-data
      containers:
      - image: quay.io/pbertera/mkdocs:latest
        imagePullPolicy: Always
        name: mkdocs-demo
        args: ["serve", "-a", "0.0.0.0:8000"]
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/data
          name: mkdocs-data
      volumes:
      - name: mkdocs-data
        persistentVolumeClaim:
          claimName: mkdocs
