apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mkdocs-demo
  name: mkdocs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs-demo
  template:
    metadata:
      labels:
        app: mkdocs-demo
    spec:
      containers:
      - image: registry.access.redhat.com/ubi8/nginx-118
        args: ['nginx', '-g', 'daemon off;']
        imagePullPolicy: Always
        name: webserver
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: html-mkdocs
      volumes:
      - name: html-mkdocs
        persistentVolumeClaim:
          claimName: html-mkdocs
