apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mkdocs
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: main
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  - name: mkdocs-image
    description: the image for the mkdocs
    default: image-registry.openshift-image-registry.svc:5000/pipelines-demo/mkdocs
  - name: webserver-image
    description: the http server container image
  - name: webserver-container
    description: the name of the webserver container
  - name: deployment-name
    description: name of the deployment
  - name: action
    description: the action to perform
    default: build-docs
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: build-and-deploy
      params:
      - name: CONTEXT
        value: build
      - name: mkdocs-image
        value: $(tt.params.mkdocs-image)
      - name: webserver-image
        value: registry.access.redhat.com/ubi8/nginx-118
      - name: webserver-container
        value: "webserver"
      - name: deployment-name
        value: mkdocs-demo
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: action
        value: $(tt.params.action)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
      - name: html-workspace
        persistentVolumeClaim:
          claimName: html-mkdocs

